name: Build and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t vasesdas/nodejs-app:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push vasesdas/nodejs-app:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: |
        docker pull vasesdas/nodejs-app:${{ github.sha }}

    - name: setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: add SSH host
      run: |
        ssh-keyscan 192.168.105.4 >> ~/.ssh/known_hosts
        
    - name: Deploy to production
      env:
        DOCKER_HOST: ssh://vagrant@192.168.105.4
      run: |
        docker pull vasesdas/nodejs-app:${{ github.sha }}
        docker stop nodejs-app || true
        docker rm nodejs-app || true
        docker run -d --name nodejs-app -p 4444:4444 vasesdas/nodejs-app:${{ github.sha }}
